# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Lean Kanban Central Europe"

email: "lkce@it-agile.de"
description: "World's biggest conference on Lean and Kanban!"
baseurl: ""
url: "http://www.leankanbance.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "it-agile GmbH"
organizerAlternateName: "it-agile"
organizerDescription: "Consultancy for Agile methods"
organizerEmail: "lkce@it-agile.de"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.it-agile.de"

# Head
metaKeywords: "event, kanban, lean, modern management, change, it-agile, LKU, agile, hamburg"
twitterAccount: "@LeanKanbanCE"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/cfp-lkce17"
c4sponsorsUrl: "/assets/Sponsoring_LKCE17.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/socialevent/", text: "Social Event"}
 - {permalink: "/cod/", text: "Code of Conduct"}
bottomNavigationLinks:
  - {permalink: "/#tickets", text: "Buy tickets"}
rightNavigationButtons:
  - {permalink: "/#tickets", text: "Buy tickets"}

# Hero Block
heroImage: "aligned.png"
heroTitle: "Lean Kanban Central Europe <typeout>"
eventDate: "5th + 6th November, 2018"
typeoutTextValues: '"", "2018"'
typeoutFallback: "2018"
heroButtons:
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About Lean Kanban Central Europe"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "Come and join us at the world’s most popular Lean Kanban conference of this world wide series. Two days packed with inspiring talks, workshops and networking opportunities."}
 - {title: "Social Event", image: "socialevent.jpg", text: "Join us for an evening of exchanging ideas, meeting new people and your favorite speaker while having a beer!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Want to dig even deeper? Stay in Hamburg and attend one of many workshop that will take place on Nov. 9th. Stay tuned for more information!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of Lean and Kanban"}
 - {count: "30", specialCharacter: "+", info: "speakers", detail: "from all over the world"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus workshops"}

# Latest News Block
latestNewsTitle: "Latest news"

# Keynote Speakers Block
keynoteSpeakersImage: "speakers.jpg"
keynoteSpeakersCount: 3
keynoteSpeakersTitle: "Keynote Speakers LKCE2017"
keynoteSpeakersButtonText: "See all LKCE17 speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Curio-Haus"
eventLocationLink: "http://www.koflerkompanie.com/locations/hamburg/curiohaus/"
eventStreetAddress: "Rothenbaumchaussee 13"
eventAddressLocality: "Hamburg"
eventAddressLocalityRegion: "Hamburg"
eventPostalCode: "20148"
eventAddressCountry: "Germany"
eventStartTime: "2017-11-07T09:30"
eventDoorTime: "09:00"
eventEndTime: "2017-11-08T18:00"
eventPlaceCoordinates: "53.565018, 9.989006"
mapCenterCoordinates: "53.565018, 9.989006"
mapMobileCenterCoordinates: "53.565018, 9.989006"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Curio-Haus"
venueFeatures: ["3 rooms", "Lounge to relax and talk", "Located close to the Außenalster"]

# Tweets Feed Block
tweetsFeedImage: "direction-details.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "LKCE17"
twitterFeed: "http://leankanbance.com/tweetledee/searchjson.php?q=#lkce17&rt=recent"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners 2017"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of April. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee breaks, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "LKCE18 - Early Bird Ticket"
  price: "800"
  priceCurrency: "EUR (excl. 19% VAT)"
  ticketsNumber: "50"
  ribbon: ""
  buyButtonLink: "http://ti.to/lkce/lkce18"
  buyButtonText: "Buy Now - the price will go up"
  ticketContentList: ["2 Days", "3 Tracks", "Social Event"]
  validFrom: "2017-11-25T10:00"
  validThrough: "2014-09-30T23:59"

# Footer
socialLinks:
 - {link: "http://twitter.com/LeanKanbanCE", icon: "twitter"}
 - {link: "http://facebook.com/LeanKanbanCE", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://it-agile.de", text: "it-agile GmbH"}
   - {link: "http://leankanban.com", text: "Lean Kanban Inc."}
   - {permalink: "/cod/", text: "Code of Conduct"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:lkce@it-agile.de", text: "lkce@it-agile.de"}
 -
  title: "Legal"
  links:
   - {permalink: "/impressum/", text: "Impressum"}
   - {permalink: "/termsoftrade/", text: "Terms of Trade"}
   - {permalink: "/datenschutz/", text: "Datenschutz"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "lkce"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "It all started 2011 in Munich and since then Lean Kanban Central Europe grew to the biggest and most popular conference on Lean and Kanban. Our mission has always been and will be again in 2017 to host an unforgetable event for system thinkers, managers, leaders, out-of-the-box-thinkers, entrepreneurs, product developers, and people who care about the way they work."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "53.565018, 9.989006"
logisticsMapMobileCenterCoordinates: "53.565018, 9.989006"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Hamburg"
directionDetailsCards:
 - {title: "From the Airport", information: 'The airport is easily reachable by car, public transport or taxi. More information is available at <a href="http://www.hamburg-airport.de/en/bus_rail_and_transfer.php">airport website</a>.'}
 - {title: "Public Transit", information: 'Go to Hamburg Dammtor for public transportation to the central station, the airport or anywhere else in Hamburg.'}

directionDetailsWideCards:

# Logistics Hotels Block
hotelsTitle: "Hotels"

# socialevent
socialeventTitle: "Social Event"
enablesocialevent: true

# About Social Event Block
socialEventBlockTitle: "About Tropen-Aquarium Hagenbeck"
aboutSocialEvent: "In May 2007, 100 years after the opening of the world renowned zoo, Hagenbeck gave the all-clear for its new recreational attraction: the Tropical World Adventure Aquarium. That finally gives the citizens of Hamburg and the steadily growing number of tourists to the Hanseatic city an aquarium of the highest international standard. This new attraction has given Hamburg, the waterside city and “gateway to the world“, an access to the flora and fauna of the equatorial regions. For the visitor, a truly unique world of adventure opens itself up which is designed as though Carl Hagenbeck himself had done it: with barless open enclosures, right up close to the animals. Visitors can see 14,300 exotic animals in their habitat – on land, in the water and in caves.</br></br>

The concept: animals ashore, in water and in caves 300 animals live in the Tropen-Aquarium, some are endangered species from the equatorial regions. In all a total of 14,300 exotic animals have found a home here in Hamburg. The round tour leads the visitor through several theme areas: the tropical and sub-tropical seas, forests and the world of caves. This combination is unique in the world. The species-specific and close-to-nature design of the enclosures together with the fascinating presentation of the animals results in the illusion for the visitor of finding themselves transported into the middle of their habitat. In the biotopes, animals whose territory would also overlap in the wild share a habitat with each other.</br></br>

Visitors are struck by the unbelievable multiplicity of colours and forms of the living coral reef.</br></br>

The multitude of fresh and salt water pools are home to red lion fish, moray eels, unusua lschooling fish and rarities of the aquatic habitat. "

# socialevent Location Block
socialeventLocationBlockTitle: "Location"
socialeventLocationName: "Tropen-Aquarium Hagenbeck"
socialeventLocationLink: "http://www.hagenbeck.de/en/tropen-aquarium/start.html"
socialeventStreetAddress: "Lokstedter Grenzstraße 2"
socialeventAddressLocality: "Hamburg"
socialeventAddressLocalityRegion: "Hamburg"
socialeventPostalCode: "22527"
socialeventAddressCountry: "Germany"
socialeventTimeTitle: "Meet new friends"
socialeventStartTime: "2017-11-07T19:00"
socialeventDoorTime: "19:00"
socialeventEndTime: "2017-11-07T23:00"
viewOnMap: "View on Google Maps"
socialeventPlaceCoordinates: "53.5953473, 9.9394337"
socialeventMapCenterCoordinates: "53.5953473, 9.9394337"
socialeventMapMobileCenterCoordinates: "53.5953473, 9.9394337"
socialeventPlaceCoordinates: "53.5953473, 9.9394337"
socialeventMapCenterCoordinates: "53.5953473, 9.9394337"
socialeventMapMobileCenterCoordinates: "53.5953473, 9.9394337"
